server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/sys?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 #13.125.117.231    
    username: cos
    password: cos1234
logging:               
  level:
    root: info
    shutup.code.security: debug

  jpa:
    open-in-view: true
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
        use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: false
      

  jackson:
    serialization:
      fail-on-empty-beans: false


